### ISSUE TITLE
MaxRetryError?

### ISSUE THREAD

**Issue by mxwmnn** [mohankumarpaluru/oracle-freetier-instance-creation#11]
After some minutes i get the following oci lib error:
```
└─[$] <git:(main*)> python main.py
Traceback (most recent call last):
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/connection.py", line 179, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/util/connection.py", line 77, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/socket.py", line 963, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/connectionpool.py", line 708, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/connectionpool.py", line 391, in _make_request
    self._validate_conn(conn)
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/connectionpool.py", line 1045, in _validate_conn
    conn.connect()
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/connection.py", line 191, in _new_conn
    raise NewConnectionError(
oci._vendor.urllib3.exceptions.NewConnectionError: <oci.base_client.OCIConnection object at 0x74530085e870>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/requests/adapters.py", line 447, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/connectionpool.py", line 790, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/urllib3/util/retry.py", line 597, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
oci._vendor.urllib3.exceptions.MaxRetryError: OCIConnectionPool(host='identity.eu-frankfurt-1key_file.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/users/ocid1.user.oc1..aaaaaaaaa2ih535x46las6q2nxu3y57zqbe6xojgmh6rr6ru25lyfeg5pxta (Caused by NewConnectionError('<oci.base_client.OCIConnection object at 0x74530085e870>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/base_client.py", line 677, in request
    response = self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/requests/sessions.py", line 536, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/requests/sessions.py", line 652, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/_vendor/requests/adapters.py", line 527, in send
    raise ConnectionError(e, request=request)
oci._vendor.requests.exceptions.ConnectionError: (MaxRetryError("OCIConnectionPool(host='identity.eu-frankfurt-1key_file.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/users/ocid1.user.oc1..aaaaaaaaa2ih535x46las6q2nxu3y57zqbe6xojgmh6rr6ru25lyfeg5pxta (Caused by NewConnectionError('<oci.base_client.OCIConnection object at 0x74530085e870>: Failed to establish a new connection: [Errno -2] Name or service not known'))"), 'Request Endpoint: GET https://identity.eu-frankfurt-1key_file.oci.oraclecloud.com/20160918/users/ocid1.user.oc1..aaaaaaaaa2ih535x46las6q2nxu3y57zqbe6xojgmh6rr6ru25lyfeg5pxta See https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_troubleshooting.htm for help troubleshooting this error, or contact support and provide this full error message.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frmwrk/git/oracle-freetier-instance-creation/main.py", line 419, in <module>
    launch_instance()
  File "/home/frmwrk/git/oracle-freetier-instance-creation/main.py", line 327, in launch_instance
    user_info = execute_oci_command(iam_client, "get_user", OCI_USER_ID)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/main.py", line 276, in execute_oci_command
    response = getattr(client, method)(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/identity/identity_client.py", line 8285, in get_user
    return retry_strategy.make_retrying_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/retry/retry.py", line 308, in make_retrying_call
    response = func_ref(*func_args, **func_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/base_client.py", line 535, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/frmwrk/git/oracle-freetier-instance-creation/.venv/lib/python3.12/site-packages/oci/base_client.py", line 700, in request
    raise exceptions.RequestException(e)
oci.exceptions.RequestException: (MaxRetryError("OCIConnectionPool(host='identity.eu-frankfurt-1key_file.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20160918/users/ocid1.user.oc1..aaaaaaaaa2ih535x46las6q2nxu3y57zqbe6xojgmh6rr6ru25lyfeg5pxta (Caused by NewConnectionError('<oci.base_client.OCIConnection object at 0x74530085e870>: Failed to establish a new connection: [Errno -2] Name or service not known'))"), 'Request Endpoint: GET https://identity.eu-frankfurt-1key_file.oci.oraclecloud.com/20160918/users/ocid1.user.oc1..aaaaaaaaa2ih535x46las6q2nxu3y57zqbe6xojgmh6rr6ru25lyfeg5pxta See https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdk_troubleshooting.htm for help troubleshooting this error, or contact support and provide this full error message.')```

```
└─[$] <git:(main*)> cat oci.env          
# OCI Configuration
OCI_CONFIG=/home/frmwrk/git/oracle-freetier-instance-creation/oci_config
OCT_FREE_AD=AD-1,AD-2,AD-3
DISPLAY_NAME=everyone
REQUEST_WAIT_TIME_SECS=20
SSH_AUTHORIZED_KEYS_FILE=/home/frmwrk/.ssh/id_rsa.pub
# SUBNET_ID to use in case running in local or a non E2.1.Micro instance
OCI_SUBNET_ID=subnet-todaysdate-randomnumber
OCI_IMAGE_ID=
# The following will be ignored if OCI_IMAGE_ID is specified
OPERATING_SYSTEM=Canonical Ubuntu
OS_VERSION=22.04

# Gmail Notification
NOTIFY_EMAIL=False
EMAIL=abc@gmail
EMAIL_PASSWORD=16characterswithoutspaces```

oci_config copied as said and with the corresponding private key

Is my IP blacklisted? Cause on cloud web gui it works

**Comment by mxwmnn** [comment]
Solved when using the micro instance as suggested

**Comment by mohankumarpaluru** [comment]
> Solved when using the micro instance as suggested

Glad to hear it's resolved! The issue might be related to network restrictions like a proxy or VPN on your end, rather than Oracle blocking your IP since you can access the GUI. 

Also, your logs include your user OCID, consider removing it or the logs entirely since your issue appears to be resolved.
