### ISSUE TITLE
ValueError: PosixPath('.') has an empty name

### ISSUE THREAD

**Issue by Caduzin2005** [mohankumarpaluru/oracle-freetier-instance-creation#49]
**Describe the bug**
Script returns error "ValueError: PosixPath('.') has an empty name"

Here is the full error that main.py gives (mannualy activated it)

Traceback (most recent call last):
  File "/home/ubuntu/Project/CreateInstance/oracle-freetier-instance-creation/main.py", line 489, in <module>
    launch_instance()
  File "/home/ubuntu/Project/CreateInstance/oracle-freetier-instance-creation/main.py", line 423, in launch_instance
    ssh_public_key = read_or_generate_ssh_public_key(SSH_AUTHORIZED_KEYS_FILE)
  File "/home/ubuntu/Project/CreateInstance/oracle-freetier-instance-creation/main.py", line 352, in read_or_generate_ssh_public_key
    private_key_path = public_key_path.with_name(f"{public_key_path.stem}_private")
  File "/usr/lib/python3.10/pathlib.py", line 758, in with_name
    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('.') has an empty name

**Expected behavior**
Run the script as normal

**Instance Type (please complete the following information):**
 - ARM or Micro: ARM
 - Micro Second Instance: no
 - Custom Image or default: Custom, Oracle Linux 7.9

**Environment (please complete the following information):**
 - Micro Instance or Local: Micro
 - OS:  Canonical Ubuntu
 - Version: 22.04

**Screenshots**

**Additional context**
Checked oci_config, and oci.env for any typos, but the problems seens to be on pathlib

**Comment by Caduzin2005** [comment]
Figured it out, for some reason it was not getting the public key file path, just remade the oci.env file, it worked.
